name: Run Tests
on:
   push:
     branches:
       - main
   pull_request:
     branches:
       - main
jobs:
  test:
    runs-on: ubuntu-20.04
    name: Run Tests
    env:
      TESTING: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.6.8'  #Might need to be changed

      - name: Setup Python Virtual Environment
        run: python -m venv python-virtualenv

      - name: Install Dependencies
        run: python-virtualenv/bin/pip install -r requirements.txt

      - name: Run Tests
        run: ./run_test.sh
